name = "Gruvbox Dark"
variant = "dark"
font = "IBM Plex Mono"
ghostty = "Gruvbox Dark"
helix = "gruvbox"
zellij = "gruvbox-dark"
btop = "gruvbox_dark"
neovim = "gruvbox"
delta = "gruvbox-dark"
bat = "gruvbox-dark"
tmux = "gruvbox-dark"
opencode = "gruvbox"
