[mgr]
cwd = { fg = "#d5c4a1", italic = true }

# Hovered
hovered         = { bg = "#3c3836" }
preview_hovered = { bg = "#3c3836" }

# Find
find_keyword  = { fg = "#282828", bg = "#fe8019", bold = true }
find_position = { fg = "#8ec07c", bg = "#3c3836", bold = true }

# Marker
marker_copied   = { fg = "#b8bb26", bg = "#b8bb26" }
marker_cut      = { fg = "#cc241d", bg = "#cc241d" }
marker_marked   = { fg = "#b16286", bg = "#b16286" }
marker_selected = { fg = "#83a598", bg = "#83a598" }

# Count
count_copied   = { fg = "#282828", bg = "#b8bb26" }
count_cut      = { fg = "#282828", bg = "#cc241d" }
count_selected = { fg = "#282828", bg = "#83a598" }

# Border
border_symbol = "│"
border_style  = { fg = "#504945" }

# Tab
[tabs]
active   = { fg = "#282828", bg = "#83a598" }
inactive = { fg = "#83a598", bg = "#3c3836" }

[mode]
normal_main = { fg = "#282828", bg = "#83a598", bold = true }
normal_alt  = { fg = "#83a598", bg = "#3c3836" }

select_main = { fg = "#282828", bg = "#b16286", bold = true }
select_alt  = { fg = "#b16286", bg = "#3c3836" }

unset_main  = { fg = "#282828", bg = "#7c6f64", bold = true }
unset_alt   = { fg = "#7c6f64", bg = "#3c3836" }

[status]
overall   = { fg = "#ebdbb2", bg = "#1d2021" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label  = { fg = "#ebdbb2", bold = true }
progress_normal = { fg = "#504945", bg = "#3c3836" }
progress_error  = { fg = "#cc241d", bg = "#3c3836" }

# Permissions
perm_type  = { fg = "#83a598" }
perm_read  = { fg = "#fabd2f" }
perm_write = { fg = "#cc241d" }
perm_exec  = { fg = "#b8bb26" }
perm_sep   = { fg = "#504945" }

[pick]
border   = { fg = "#504945" }
active   = { fg = "#ebdbb2",  bg = "#3c3836" }
inactive = { fg = "#ebdbb2" }

# Input
[input]
border   = { fg = "#8ec07c" }
title    = { fg = "#8ec07c" }
value    = { fg = "#b16286" }
selected = { bg = "#3c3836" }

# Completion
[cmp]
border   = { fg = "#8ec07c" }
active   = { fg = "#ebdbb2", bg = "#504945" }
inactive = { fg = "#ebdbb2" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#504945" }
title   = { fg = "#504945" }
hovered = { fg = "#ebdbb2", bg = "#3c3836" }

# Which
[which]
cols            = 3
mask            = { bg = "#1d2021" }
cand            = { fg = "#8ec07c" }
rest            = { fg = "#83a598" }
desc            = { fg = "#b16286" }
separator       = " ➜ "
separator_style = { fg = "#7c6f64" }

# Confirm
[confirm]
border  = { fg = "#8ec07c" }
title   = { fg = "#504945" }
content = {}
list    = {}
btn_yes = { bg = "#3c3836" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#504945" }
title   = { fg = "#504945" }

# Notify
[notify]
title_info  = { fg = "#8ec07c" }
title_warn  = { fg = "#fabd2f" }
title_error = { fg = "#cc241d" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#b8bb26" }
run     = { fg = "#b16286" }
desc    = { fg = "#8ec07c" }
hovered = { bg = "#3c3836" }
footer  = { fg = "#ebdbb2", bg = "#282828" }

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#fabd2f" },

	# Media
	{ mime = "{audio,video}/*", fg = "#b16286" },

	# Archives
	{ mime = "application/*zip", fg = "#cc241d" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#cc241d" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#8ec07c" },

	# Special files
	{ name = "*", is = "orphan", bg = "#cc241d" },
	{ name = "*", is = "exec"  , fg = "#b8bb26" },

	# Fallback
	{ name = "*/", fg = "#83a598" },
	{ name = "*", fg = "#ebdbb2" }
]
