name = "Kanagawa Wave"
variant = "dark"
ghostty = "Kanagawa Wave"
helix = "kanagawa"
zellij = "kanagawa-wave"
btop = "kanagawa_wave"
neovim = "kanagawa-wave"
delta = "kanagawa-wave"
bat = "Kanagawa"
tmux = "kanagawa-wave"
opencode = "kanagawa"
