name = "Catppuccin Mocha"
variant = "dark"
font = "JetBrains Mono"
ghostty = "Catppuccin Mocha"
helix = "catppuccin_mocha"
zellij = "catppuccin-mocha"
btop = "catppuccin_mocha"
neovim = "catppuccin-mocha"
delta = "catppuccin-mocha"
bat = "Catppuccin Mocha"
tmux = "mocha"
opencode = "catppuccin-mocha-glass"
