name = "Tokyo Night"
variant = "dark"
font = "JetBrains Mono"
ghostty = "TokyoNight Night"
helix = "tokyonight_night"
zellij = "tokyonight-night"
btop = "tokyonight_night"
neovim = "tokyonight-night"
delta = "tokyonight-night"
bat = "TokyoNight"
tmux = "tokyonight-night"
opencode = "tokyonight"
