[[mgr.prepend_keymap]]
on   = "T"
run  = '''shell 'bash ~/.config/yazi/scripts/open-typora.sh "$@"' '''
desc = "Open in Typora"

[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = '''shell 'bash ~/.config/yazi/scripts/open-editor.sh "$@"' --block'''
desc = "Open in floating pane (90%)"

[[mgr.prepend_keymap]]
on   = "e"
run  = '''shell 'glow -p -w 80 "$@"' --block'''
desc = "View with glow"
