[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = '''shell 'bash ~/.config/yazi/scripts/open-editor.sh "$@"' --block'''
desc = "Open in floating pane (90%)"

[[mgr.prepend_keymap]]
on   = "e"
run  = '''shell 'glow -p "$@"' --block'''
desc = "View with glow"
