[[mgr.prepend_keymap]]
on   = "F"
run  = 'shell "open -R $@" --confirm'
desc = "Reveal in Finder"

[[mgr.prepend_keymap]]
on   = "T"
run  = '''shell 'bash ~/.config/yazi/scripts/open-typora.sh "$@"' '''
desc = "Open in Typora"

[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = '''shell 'bash ~/.config/yazi/scripts/open-editor.sh "$@"' --block'''
desc = "Open in floating pane (90%)"

[[mgr.prepend_keymap]]
on   = "e"
run  = '''shell 'glow -p -w 80 "$@"' --block'''
desc = "View with glow"

[[mgr.prepend_keymap]]
on   = ["g", "n"]
run  = 'shell "nvim ." --block'
desc = "Open nvim in current directory"

[[mgr.prepend_keymap]]
on   = ["g", "i"]
run  = "plugin lazygit"
desc = "Open lazygit"

[[mgr.prepend_keymap]]
on   = ["y", "c"]
run  = 'shell "pbcopy < $0" --confirm'
desc = "Copy file contents to clipboard"
